version: "3"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: parking
    ports:
      - "5432:5432"
  frontend:
    build: ./front
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      REACT_APP_API_URL: http://localhost:4000/graphql
    volumes:
      - "./front:/usr/src/app/front"
      - "/usr/src/app/front/node_modules"
  backend:
    build: ./back
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    environment:
      JWT_SECRET: 2312hsdjfhhdkjsaeaihwef3423
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: parking
      POSTGRES_HOST: postgres
    restart: always
    volumes:
      - ./back:/usr/src/app/back
      - /usr/src/app/back/node_modules
