FROM node:14.17.2

RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/front

WORKDIR /usr/src/app/front

COPY package*.json ./
RUN npm install -g create-react-app
RUN npm update
RUN npm install 

COPY . .

ENV REACT_APP_API_URL=$REACT_APP_API_URL

EXPOSE 3000

# Command to run our app
CMD [ "npm", "run","start" ]